#!/bin/bash
#
# Step-by-Step Execution Guide
# Follow these commands in order
#

echo "🎯 Browser Optimization - Execution Steps"
echo "=========================================="
echo ""

echo "STEP 1: Activate Setup"
echo "----------------------"
echo "Run: source ~/.dotfiles/setup.sh"
echo ""
echo "This will:"
echo "  • Make all scripts executable"
echo "  • Reload shell functions"
echo "  • Show available commands"
echo ""
echo "Press Enter when complete..."
read

echo ""
echo "STEP 2: Test Commands"
echo "---------------------"
echo "Run these to verify setup:"
echo "  browsermem    # Show browser memory"
echo "  gpustatus     # Check GPU status"
echo ""
echo "Press Enter when complete..."
read

echo ""
echo "STEP 3: Install Notion"
echo "----------------------"
echo "Choose one option:"
echo ""
echo "Option A (Recommended):"
echo "  1. Open: https://www.notion.so/desktop"
echo "  2. Download and install"
echo "  3. Close Notion web tab in browser"
echo ""
echo "Option B (Homebrew):"
echo "  brew update"
echo "  brew install --cask notion"
echo ""
echo "Press Enter when complete..."
read

echo ""
echo "STEP 4: Enable GPU Flags"
echo "------------------------"
echo "For each browser (Arc, Dia, Chrome):"
echo ""
echo "1. Open flags page:"
echo "   Arc:    arc://flags/"
echo "   Dia:    dia://flags/"
echo "   Chrome: chrome://flags/"
echo ""
echo "2. Search and enable these 4 flags:"
echo "   • enable-gpu-rasterization"
echo "   • enable-zero-copy"
echo "   • ui-enable-shared-image-cache-for-gpu"
echo "   • use-angle-metal"
echo ""
echo "3. Click 'Relaunch' button"
echo ""
echo "Press Enter when complete..."
read

echo ""
echo "STEP 5: Install OneTab"
echo "----------------------"
echo "In each browser:"
echo "  1. Go to extension store"
echo "  2. Search 'OneTab'"
echo "  3. Install and pin to toolbar"
echo ""
echo "Press Enter when complete..."
read

echo ""
echo "STEP 6: Disable Speechify"
echo "-------------------------"
echo "In browser with Speechify:"
echo "  1. Go to Extensions"
echo "  2. Find Speechify"
echo "  3. Disable or Remove"
echo "  Saves: 380MB"
echo ""
echo "Press Enter when complete..."
read

echo ""
echo "STEP 7: Apply macOS Settings"
echo "----------------------------"
echo "Run: ~/.dotfiles/macos/memory-optimize.sh"
echo ""
echo "This will:"
echo "  • Reduce transparency and motion"
echo "  • Auto-hide Dock and menu bar"
echo "  • Optimize Spotlight"
echo "  • Disable unused services"
echo ""
echo "Press Enter when complete..."
read

echo ""
echo "STEP 8: Verify Results"
echo "----------------------"
echo "Run these commands:"
echo "  gpustatus     # Check memory pressure"
echo "  browsermem    # Check browser memory"
echo ""
echo "Expected results:"
echo "  • Memory Pressure: GREEN"
echo "  • Browser Memory: < 12GB (down from 23GB)"
echo "  • Swap Usage: < 2GB"
echo ""
echo "Press Enter when complete..."
read

echo ""
echo "✅ All steps complete!"
echo ""
echo "📊 Final verification:"
echo "  gpustatus"
echo ""
