tap "goles/battery"
tap "homebrew/bundle"
tap "homebrew/core"

brew 'awscli'
brew "bat"
brew "bats-core"
brew "coreutils"
brew "diff-so-fancy"
brew "dockutil"
brew "fasd"
brew "ffmpeg"
brew "gh"
brew "gnu-sed"
brew "gnupg"
brew "goles/battery/battery"
brew "grep"
brew "grip"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "lynx"
brew "mackup"
brew "nano"
brew "pandoc"
brew "peco"
brew "psgrep"
brew "python"
brew "shellcheck"
brew "ssh-copy-id"
brew "stow"
brew "thefuck"
brew "tree"
brew "wget"


# mas '1Password7', id: 1333542190
# mas 'Feedly', id: 865500966
# mas 'Keynote', id: 409183694
# mas 'Numbers', id: 409203825
# mas 'Pages', id: 409201541
# mas 'Pocket', id: 568494494
# mas 'todoist', id: 585829637
# mas 'Trello', id: 1278508951
# mas 'TweetDeck', id: 485812721
# # mas 'Twitter', id: 1482454543
# # mas 'Unsplash Wallpapers', id: 1284863847
# # mas 'WebP Converter', id: 1522368690
# mas 'Xcode', id: 497799835
# mas "LINE", id: 539883307
# mas "Slack", id: 803453959
# mas "magnet", id: 441258766